# Generated by Django 4.1.3 on 2022-11-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(default=None, max_length=30)),
                ('banner_image', models.ImageField(default=None, upload_to='banner/')),
            ],
        ),
    ]
