# Generated by Django 4.1.3 on 2022-11-27 05:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddField',
            fields=[
                ('orders_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.orders')),
                ('order_time', models.TimeField(default=datetime.datetime(2022, 11, 27, 11, 27, 1, 128487))),
                ('product_qty', models.IntegerField(default=None)),
                ('product_total', models.IntegerField(default=None)),
            ],
            bases=('home.orders',),
        ),
    ]
