# Generated by Django 4.1.3 on 2022-11-28 06:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('phone_number', models.BigIntegerField(default=None)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('address', models.TextField(default=None)),
                ('state', models.CharField(default=None, max_length=30)),
                ('pincode', models.IntegerField(default=None)),
                ('city', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='orderaddfield',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 28, 11, 51, 39, 944586)),
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_image', models.ImageField(default=None, upload_to='orders/')),
                ('product_price', models.IntegerField(default=None)),
                ('product_discription', models.TextField(default=None)),
                ('order_date', models.DateField()),
                ('order_time', models.TimeField(default=datetime.datetime(2022, 11, 28, 11, 51, 39, 944586))),
                ('product_qty', models.IntegerField(default=None)),
                ('product_total', models.IntegerField(default=None)),
                ('is_cancel', models.BooleanField(default=None)),
                ('is_delivered', models.BooleanField(default=None)),
                ('payment_type', models.CharField(max_length=10)),
                ('address', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='payment.orderaddress')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logins.userinfo')),
            ],
        ),
    ]
