# Generated by Django 4.1.3 on 2022-11-29 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_orderaddress_alter_orderaddfield_order_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='is_payment',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='orderaddfield',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 29, 12, 18, 26, 412888)),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 29, 12, 18, 26, 412888)),
        ),
    ]
