# Generated by Django 4.1.3 on 2022-11-30 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_orderlist_is_payment_alter_orderaddfield_order_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddfield',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 30, 12, 35, 8, 125737)),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 30, 12, 35, 8, 125737)),
        ),
    ]
