# Generated by Django 4.1.2 on 2022-12-08 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_orderaddfield_order_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_off', models.IntegerField(default=None)),
                ('c_name', models.CharField(default=None, max_length=30)),
                ('c_description', models.TextField(default=None)),
                ('is_use', models.BooleanField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='orderaddfield',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2022, 12, 8, 14, 48, 42, 980372)),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2022, 12, 8, 14, 48, 42, 980372)),
        ),
    ]
