# Generated by Django 4.1.2 on 2022-12-13 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_orderlist_order_pack_alter_orderaddfield_order_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddfield',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2022, 12, 13, 11, 6, 4, 65934)),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2022, 12, 13, 11, 6, 4, 65934)),
        ),
    ]
