# Generated by Django 4.1.3 on 2022-11-27 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=20)),
                ('product_name', models.CharField(default=None, max_length=50)),
                ('product_image', models.ImageField(default=None, upload_to='orders/')),
                ('product_price', models.IntegerField(default=None)),
                ('product_discription', models.TextField(default=None)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_type', models.CharField(default=None, max_length=20)),
                ('user_address', models.TextField(default=None)),
                ('user_phone', models.BigIntegerField(default=None)),
                ('user_state', models.CharField(default=None, max_length=30)),
                ('user_pincode', models.IntegerField(default=None)),
                ('user_email', models.EmailField(default=None, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default=None, max_length=50)),
                ('product_price', models.IntegerField(default=None)),
                ('product_image', models.ImageField(default=None, upload_to='images/')),
                ('product_discription', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_quantity', models.IntegerField(default=None)),
                ('total_price', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default=None)),
                ('rate', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ProductWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
